import { NextResponse } from "next/server";

const posts = [
  { id: "1", slug: "ai-chatbots-boost-ecommerce", title: "How AI Chatbots Boost E-commerce Conversion Rates", excerpt: "Discover how intelligent chatbots are transforming online shopping with personalized assistance and 24/7 availability.", content: "E-commerce is evolving rapidly. AI chatbots are now capable of understanding customer intent, recommending products, and closing sales without human intervention. Studies show that stores using AI chatbots see a 24% increase in average order value and a 35% reduction in cart abandonment.\n\n## Why Chatbots Work\n\n- **24/7 Availability**: Answer customer questions at any time\n- **Personalization**: Remember preferences and browsing history\n- **Instant Response**: No waiting for email or phone support\n- **Scalability**: Handle thousands of conversations simultaneously\n\n## Implementation Tips\n\n1. Start with common FAQ automation\n2. Add product recommendation capabilities\n3. Integrate with your inventory system\n4. Escalate complex queries to human agents\n\nCircuCity AI makes this easy with our plug-and-play widget.", date: "2025-06-01", author: "CircuCity Team", category: "Product", image: null },
  { id: "2", slug: "sustainable-ecommerce-trends-2025", title: "Sustainable E-commerce Trends for 2025", excerpt: "The future of online retail is green. Here's what's shaping sustainable commerce this year.", content: "Sustainability is no longer optional. Consumers are demanding eco-friendly options and transparent supply chains.\n\n## Key Trends\n\n- **Carbon-neutral shipping**\n- **Circular economy models**\n- **Sustainable packaging**\n- **Green hosting and infrastructure**\n\nCircuCity AI helps businesses reduce their carbon footprint through efficient automation that cuts server usage and optimizes customer interactions.", date: "2025-05-28", author: "Sustainability Team", category: "Industry", image: null },
  { id: "3", slug: "customer-support-automation-guide", title: "A Complete Guide to Customer Support Automation", excerpt: "Learn how to automate your support workflow without losing the human touch.", content: "Customer support is one of the most resource-intensive parts of any business. Automation can help.\n\n## What to Automate\n\n- **FAQ responses** — instant answers to common questions\n- **Order tracking** — automated status updates\n- **Return processing** — guided return flows\n- **Appointment scheduling** — calendar integration\n\n## What NOT to Automate\n\n- Complex complaints\n- Emotional situations\n- Legal matters\n\nWith CircuCity AI, you can strike the perfect balance between automated efficiency and human empathy.", date: "2025-05-20", author: "Support Team", category: "Guide", image: null },
  { id: "4", slug: "multilingual-ai-chatbots", title: "Multilingual AI Chatbots: Breaking Language Barriers", excerpt: "How AI-powered translation is enabling businesses to serve customers in any language.", content: "The internet is global, but customer service often isn't. Multilingual AI chatbots change that.\n\n## Supported Languages\n\nCircuCity AI supports over 50 languages including Swedish, English, German, French, Spanish, Finnish, Danish, Norwegian, and many more.\n\n## How It Works\n\nOur AI detects the customer's language automatically and responds in kind. No configuration needed — just plug in and start serving customers worldwide.", date: "2025-05-15", author: "Engineering Team", category: "Product", image: null },
  { id: "5", slug: "getting-started-circucity-ai", title: "Getting Started with CircuCity AI: A Step-by-Step Guide", excerpt: "Everything you need to know to set up your first AI chatbot in under 5 minutes.", content: "Welcome to CircuCity AI! This guide will walk you through setting up your first chatbot.\n\n## Step 1: Create Your Account\n\nSign up at chatbot.circucity.se with your email and password.\n\n## Step 2: Configure Your Store\n\nAdd your store name, URL, and industry. This helps our AI understand your business context.\n\n## Step 3: Customize Your Widget\n\nChoose colors, position, welcome message, and tone. Match your brand perfectly.\n\n## Step 4: Embed on Your Site\n\nCopy the embed code and paste it into your website. Done! Your AI assistant is live.\n\nNeed help? Contact support@circucity.se.", date: "2025-05-10", author: "CircuCity Team", category: "Guide", image: null },
  { id: "6", slug: "ai-and-data-privacy", title: "AI and Data Privacy: What Businesses Need to Know", excerpt: "Understanding the intersection of artificial intelligence and data protection regulations.", content: "As AI becomes more prevalent in customer service, data privacy concerns grow.\n\n## GDPR Compliance\n\nCircuCity AI is fully GDPR compliant. All data is processed and stored on EU-based servers in Skellefteå, Sweden.\n\n## Key Protections\n\n- End-to-end encryption\n- Data anonymization options\n- Right to deletion\n- Data Processing Agreements (DPA)\n\n## Our Commitment\n\nWe never use your customer data to train our models. Your data is your data — always.", date: "2025-05-05", author: "Legal Team", category: "Industry", image: null },
];

export async function GET() {
  return NextResponse.json(posts.map(({ content, ...p }) => p));
}
